# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Set which Vagrant "box" (base image) to use, and tell it how to set up the
  # VM, packages to install, etc.
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"

  # Additional parameters for the VM
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
  end

  # Share the Phoenix/dist folder so the VM can get the source tarball and has
  # a place to put the build results.
  config.vm.synced_folder "../../dist", "/home/vagrant/dist"

  # And share a folder with the build script
  config.vm.synced_folder "../scripts", "/home/vagrant/scripts"

  # set auto_update to false, if you do NOT want to check the correct 
  # additions version when booting this machine
  config.vbguest.auto_update = false

end
