# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Set which Vagrant "box" (base image) to use, and tell it how to set up the
  # VM, packages to install, etc.
  config.vm.box = "fedora/26-cloud-base"
  config.vm.box_version = "20170705"
  config.vm.provision :shell, path: "first_time_setup.sh"
  config.vm.provision :shell, path: "bootstrap.sh"

  # Additional parameters for the VM
  config.vm.provider "virtualbox" do |vb|
      # vb.memory = 4096
      vb.memory = 1024
      # vb.cpus = 4
      vb.cpus = 2
  end

  # Share the Phoenix/dist folder so the VM can get the source tarball and has
  # a place to put the build results.
  config.vm.synced_folder "../../dist", "/home/vagrant/dist"

  # And share a folder with the build script
  config.vm.synced_folder "../scripts", "/home/vagrant/scripts"

end
