jobs:
- job: Linux_CI
  timeoutInMinutes: 90
  displayName: 'Linux CI'
  pool:
    vmImage: 'Ubuntu 20.04'
  strategy:
    matrix:
      Py37:
        python.version: '3.7'
      Py38:
        python.version: '3.8'
      Py39:
        python.version: '3.9'
      Py310:
        python.version: '3.10'

  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      sudo apt-get update
      sudo apt-get install -y build-essential
      sudo apt-get install -y libgtk-3-dev libjpeg-dev libtiff-dev \
              libsdl2-dev libgstreamer-plugins-base1.0-dev libnotify-dev \
              libsm-dev libwebkit2gtk-4.0-dev libxtst-dev libexpat1-dev \
              libgl1-mesa-dev libglu1-mesa-dev libcurl4-openssl-dev \
              libgstreamer-plugins-bad1.0-dev
    displayName: 'Install deb package requirements'

  - script: |
      python -m pip install -U pip setuptools wheel
      python -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      python build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      python build.py dox etg --nodoc sip
    displayName: 'generate code'

  - script: |
      python build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      python build.py bdist_wheel
      python build.py install
      python -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
