jobs:
- job: MacOS_CI
  timeoutInMinutes: 90
  displayName: 'MacOS CI'
  pool:
    vmImage: 'macOS-11'
  strategy:
    matrix:
      Py37:
        python.version: '3.7'
      Py38:
        python.version: '3.8'
      Py39:
        python.version: '3.9'
      Py310:
        python.version: '3.10'

  variables:
    PYTHONUNBUFFERED: '1'
    CCACHE_DIR: $(Pipeline.Workspace)/ccache

  steps:
  - checkout: self
    submodules: recursive

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      brew install ccache
      echo "##vso[task.prependpath]/usr/local/opt/ccache/libexec"
    displayName: 'Install brew package requirements & setup ccache'

  - task: Cache@2
    inputs:
      key: 'ccache | "$(Agent.OS)" | "$(python.version)" | "$(Build.BuildNumber)"'
      path: $(CCACHE_DIR)
      restoreKeys: |
        ccache | "$(Agent.OS)" | "$(python.version)"
    displayName: ccache

  - script: |
      python -m pip install -U setuptools wheel
      python -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      xcode-select --print-path
      python build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      python build.py dox etg --nodoc sip
    displayName: 'generate code'

  - script: |
      python build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      python build.py bdist_wheel
      python -m pip install dist/wxPython-*.whl
      python -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
