jobs:
- job: MacOS_CI
  timeoutInMinutes: 90
  displayName: 'MacOS CI'
  pool:
    vmImage: 'macOS-11'
  strategy:
    matrix:
      Py37:
        python.version: '3.7'
      Py38:
        python.version: '3.8'
      Py39:
        python.version: '3.9'
      Py310:
        python.version: '3.10'


  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python -m pip install -U setuptools wheel
      python -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      xcode-select --print-path
      python build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      python build.py dox etg --nodoc sip
    displayName: 'generate code'

  - script: |
      python build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      python build.py bdist_wheel
      python build.py install
      python -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
