# mypy settings for running stubtest, see check_stubs.py

[mypy]
# stubtest won't run if mypy finds errors in the stubs, and they still have
# errors of these kinds (see baseline.json)
disable_error_code =
    arg-type, assignment, attr-defined, has-type, misc, name-defined, no-redef,
    operator, overload-cannot-match, override, union-attr, valid-type, var-annotated
