/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12-snapshot-93040d2c716c
 *
 *     Copyright: (c) 2010 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"

#line 17 "sip/gen/tracker.sip"
    #include <wx/tracker.h>
#line 15 "sip_corewxTrackable.cpp"



/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_wxTrackable(void *, const sipTypeDef *);}
static void *cast_wxTrackable(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_wxTrackable)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxTrackable(void *, int);}
static void release_wxTrackable(void *,int)
{
}


sipClassTypeDef sipTypeDef__core_wxTrackable = {
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_CLASS,
        sipNameNr_wxTrackable,
        {0}
    },
    {
        sipNameNr_Trackable,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    release_wxTrackable,
    cast_wxTrackable,
    0,
    0,
    0
};
