/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12-snapshot-93040d2c716c
 *
 *     Copyright: (c) 2010 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"




/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_wxWindow(void *, const sipTypeDef *);}
static void *cast_wxWindow(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_wxWindow)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxWindow(void *, int);}
static void release_wxWindow(void *,int)
{
}


sipClassTypeDef sipTypeDef__core_wxWindow = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_wxWindow,
        {0}
    },
    {
        sipNameNr_Window,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    release_wxWindow,
    cast_wxWindow,
    0,
    0,
    0
};
