/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12-snapshot-93040d2c716c
 *
 *     Copyright: (c) 2010 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"

#line 460 "sip/gen/event.sip"
    #include <wx/event.h>
#line 15 "sip_corewxEraseEvent.cpp"

#line 40 "sip/gen/object.sip"
    #include <wx/object.h>
#line 19 "sip_corewxEraseEvent.cpp"
#line 129 "sip/gen/event.sip"
    #include <wx/event.h>
#line 22 "sip_corewxEraseEvent.cpp"
#line 17 "sip/gen/object.sip"
    #include <wx/object.h>
#line 25 "sip_corewxEraseEvent.cpp"
#line 84 "sip/gen/object.sip"
    #include <wx/object.h>
#line 28 "sip_corewxEraseEvent.cpp"


class sipwxEraseEvent : public wxEraseEvent
{
public:
    sipwxEraseEvent(int,wxDC *);
    sipwxEraseEvent(const wxEraseEvent&);
    virtual ~sipwxEraseEvent();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    wxEvent * Clone();
    wxEventCategory GetEventCategory();
    wxClassInfo * GetClassInfo();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxEraseEvent(const sipwxEraseEvent &);
    sipwxEraseEvent &operator = (const sipwxEraseEvent &);

    char sipPyMethods[3];
};

sipwxEraseEvent::sipwxEraseEvent(int id,wxDC *dc): wxEraseEvent(id,dc), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxEraseEvent::sipwxEraseEvent(const wxEraseEvent& a0): wxEraseEvent(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxEraseEvent::~sipwxEraseEvent()
{
    sipCommonDtor(sipPySelf);
}

wxEvent * sipwxEraseEvent::Clone()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_Clone);

    if (!sipMeth)
        return wxEvent::Clone();

    extern wxEvent * sipVH__core_1(sip_gilstate_t,PyObject *);

    return sipVH__core_1(sipGILState,sipMeth);
}

wxEventCategory sipwxEraseEvent::GetEventCategory()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_GetEventCategory);

    if (!sipMeth)
        return wxEvent::GetEventCategory();

    extern wxEventCategory sipVH__core_0(sip_gilstate_t,PyObject *);

    return sipVH__core_0(sipGILState,sipMeth);
}

wxClassInfo * sipwxEraseEvent::GetClassInfo()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_GetClassInfo);

    if (!sipMeth)
        return wxObject::GetClassInfo();

    extern wxClassInfo * sipVH__core_6(sip_gilstate_t,PyObject *);

    return sipVH__core_6(sipGILState,sipMeth);
}


PyDoc_STRVAR(doc_wxEraseEvent_GetDC, "EraseEvent.GetDC() -> DC");

extern "C" {static PyObject *meth_wxEraseEvent_GetDC(PyObject *, PyObject *);}
static PyObject *meth_wxEraseEvent_GetDC(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        wxEraseEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_wxEraseEvent, &sipCpp))
        {
            wxDC *sipRes;

            try
            {
            sipRes = sipCpp->GetDC();
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            return sipConvertFromType(sipRes,sipType_wxDC,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_EraseEvent, sipName_GetDC, doc_wxEraseEvent_GetDC);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_wxEraseEvent(void *, const sipTypeDef *);}
static void *cast_wxEraseEvent(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_wxEraseEvent)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_wxEvent)->ctd_cast((wxEvent *)(wxEraseEvent *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxEraseEvent(void *, int);}
static void release_wxEraseEvent(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxEraseEvent *>(sipCppV);
    else
        delete reinterpret_cast<wxEraseEvent *>(sipCppV);
}


extern "C" {static void dealloc_wxEraseEvent(sipSimpleWrapper *);}
static void dealloc_wxEraseEvent(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipwxEraseEvent *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_wxEraseEvent(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_wxEraseEvent(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_wxEraseEvent(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxEraseEvent *sipCpp = 0;

    {
        int id = 0;
        wxDC * dc = 0;

        static const char *sipKwdList[] = {
            sipName_id,
            sipName_dc,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|iJ8", &id, sipType_wxDC, &dc))
        {
            try
            {
            sipCpp = new sipwxEraseEvent(id,dc);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const wxEraseEvent * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_wxEraseEvent, &a0))
        {
            try
            {
            sipCpp = new sipwxEraseEvent(*a0);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_wxEraseEvent[] = {{19, 255, 1}};


static PyMethodDef methods_wxEraseEvent[] = {
    {SIP_MLNAME_CAST(sipName_GetDC), meth_wxEraseEvent_GetDC, METH_VARARGS, SIP_MLDOC_CAST(doc_wxEraseEvent_GetDC)}
};

sipVariableDef variables_wxEraseEvent[] = {
    {PropertyVariable, sipName_DC, &methods_wxEraseEvent[0], NULL, NULL, NULL},
};

PyDoc_STRVAR(doc_wxEraseEvent, "\1EraseEvent(int id=0, DC dc=None)\n"
    "EraseEvent(EraseEvent)");


sipClassTypeDef sipTypeDef__core_wxEraseEvent = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_wxEraseEvent,
        {0}
    },
    {
        sipNameNr_EraseEvent,
        {0, 0, 1},
        1, methods_wxEraseEvent,
        0, 0,
        1, variables_wxEraseEvent,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_wxEraseEvent,
    -1,
    -1,
    supers_wxEraseEvent,
    0,
    init_wxEraseEvent,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_wxEraseEvent,
    0,
    0,
    0,
    release_wxEraseEvent,
    cast_wxEraseEvent,
    0,
    0,
    0
};
