/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12-snapshot-93040d2c716c
 *
 *     Copyright: (c) 2010 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_core.h"

#line 1418 "sip/gen/event.sip"
    #include <wx/event.h>
#line 15 "sip_corewxWindowDestroyEvent.cpp"

#line 40 "sip/gen/object.sip"
    #include <wx/object.h>
#line 19 "sip_corewxWindowDestroyEvent.cpp"
#line 129 "sip/gen/event.sip"
    #include <wx/event.h>
#line 22 "sip_corewxWindowDestroyEvent.cpp"
#line 17 "sip/gen/object.sip"
    #include <wx/object.h>
#line 25 "sip_corewxWindowDestroyEvent.cpp"
#line 84 "sip/gen/object.sip"
    #include <wx/object.h>
#line 28 "sip_corewxWindowDestroyEvent.cpp"


class sipwxWindowDestroyEvent : public wxWindowDestroyEvent
{
public:
    sipwxWindowDestroyEvent(wxWindow *);
    sipwxWindowDestroyEvent(const wxWindowDestroyEvent&);
    virtual ~sipwxWindowDestroyEvent();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    wxEvent * Clone();
    wxEventCategory GetEventCategory();
    wxClassInfo * GetClassInfo();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxWindowDestroyEvent(const sipwxWindowDestroyEvent &);
    sipwxWindowDestroyEvent &operator = (const sipwxWindowDestroyEvent &);

    char sipPyMethods[3];
};

sipwxWindowDestroyEvent::sipwxWindowDestroyEvent(wxWindow *win): wxWindowDestroyEvent(win), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxWindowDestroyEvent::sipwxWindowDestroyEvent(const wxWindowDestroyEvent& a0): wxWindowDestroyEvent(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipwxWindowDestroyEvent::~sipwxWindowDestroyEvent()
{
    sipCommonDtor(sipPySelf);
}

wxEvent * sipwxWindowDestroyEvent::Clone()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_Clone);

    if (!sipMeth)
        return wxEvent::Clone();

    extern wxEvent * sipVH__core_1(sip_gilstate_t,PyObject *);

    return sipVH__core_1(sipGILState,sipMeth);
}

wxEventCategory sipwxWindowDestroyEvent::GetEventCategory()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_GetEventCategory);

    if (!sipMeth)
        return wxEvent::GetEventCategory();

    extern wxEventCategory sipVH__core_0(sip_gilstate_t,PyObject *);

    return sipVH__core_0(sipGILState,sipMeth);
}

wxClassInfo * sipwxWindowDestroyEvent::GetClassInfo()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_GetClassInfo);

    if (!sipMeth)
        return wxObject::GetClassInfo();

    extern wxClassInfo * sipVH__core_6(sip_gilstate_t,PyObject *);

    return sipVH__core_6(sipGILState,sipMeth);
}


PyDoc_STRVAR(doc_wxWindowDestroyEvent_GetWindow, "WindowDestroyEvent.GetWindow() -> Window");

extern "C" {static PyObject *meth_wxWindowDestroyEvent_GetWindow(PyObject *, PyObject *);}
static PyObject *meth_wxWindowDestroyEvent_GetWindow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        wxWindowDestroyEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_wxWindowDestroyEvent, &sipCpp))
        {
            wxWindow *sipRes;

            try
            {
            sipRes = sipCpp->GetWindow();
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            return sipConvertFromType(sipRes,sipType_wxWindow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_WindowDestroyEvent, sipName_GetWindow, doc_wxWindowDestroyEvent_GetWindow);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_wxWindowDestroyEvent(void *, const sipTypeDef *);}
static void *cast_wxWindowDestroyEvent(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_wxWindowDestroyEvent)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_wxCommandEvent)->ctd_cast((wxCommandEvent *)(wxWindowDestroyEvent *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxWindowDestroyEvent(void *, int);}
static void release_wxWindowDestroyEvent(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxWindowDestroyEvent *>(sipCppV);
    else
        delete reinterpret_cast<wxWindowDestroyEvent *>(sipCppV);
}


extern "C" {static void dealloc_wxWindowDestroyEvent(sipSimpleWrapper *);}
static void dealloc_wxWindowDestroyEvent(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipwxWindowDestroyEvent *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_wxWindowDestroyEvent(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_wxWindowDestroyEvent(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_wxWindowDestroyEvent(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxWindowDestroyEvent *sipCpp = 0;

    {
        wxWindow * win = 0;

        static const char *sipKwdList[] = {
            sipName_win,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|J8", sipType_wxWindow, &win))
        {
            try
            {
            sipCpp = new sipwxWindowDestroyEvent(win);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const wxWindowDestroyEvent * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_wxWindowDestroyEvent, &a0))
        {
            try
            {
            sipCpp = new sipwxWindowDestroyEvent(*a0);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_wxWindowDestroyEvent[] = {{9, 255, 1}};


static PyMethodDef methods_wxWindowDestroyEvent[] = {
    {SIP_MLNAME_CAST(sipName_GetWindow), meth_wxWindowDestroyEvent_GetWindow, METH_VARARGS, SIP_MLDOC_CAST(doc_wxWindowDestroyEvent_GetWindow)}
};

sipVariableDef variables_wxWindowDestroyEvent[] = {
    {PropertyVariable, sipName_Window, &methods_wxWindowDestroyEvent[0], NULL, NULL, NULL},
};

PyDoc_STRVAR(doc_wxWindowDestroyEvent, "\1WindowDestroyEvent(Window win=None)\n"
    "WindowDestroyEvent(WindowDestroyEvent)");


sipClassTypeDef sipTypeDef__core_wxWindowDestroyEvent = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_wxWindowDestroyEvent,
        {0}
    },
    {
        sipNameNr_WindowDestroyEvent,
        {0, 0, 1},
        1, methods_wxWindowDestroyEvent,
        0, 0,
        1, variables_wxWindowDestroyEvent,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_wxWindowDestroyEvent,
    -1,
    -1,
    supers_wxWindowDestroyEvent,
    0,
    init_wxWindowDestroyEvent,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_wxWindowDestroyEvent,
    0,
    0,
    0,
    release_wxWindowDestroyEvent,
    cast_wxWindowDestroyEvent,
    0,
    0,
    0
};
