
        def DoSomething(self):
            # block all events directed to this window while
            # we do the 1000 FunctionWhichSendsEvents() calls
            with wx.EventBlocker(self) as blocker:

                for i in xrange(1000):
                    FunctionWhichSendsEvents(i)

            # wx.EventBlocker destructor called on exit from the context
            # manager, old event handlers are restored.

            # the event generated by this call will be processed:
            FunctionWhichSendsEvents(0)

