# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: file
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: 'Tree docs, can be anything you want....'
# - width: 70


"""
Tree docs, can be anything you want.
"""


class test_import_export_no_change2:
    """
    Root topic 1.
    """

    class subtopic_1:
        """
        Sub topic 1 of root topic. Docs rely on one blank line for
        topic doc, and indentation for each argument doc.
        """
        
        def msgDataSpec(arg1, arg2=None):
            """
            - arg1: some multiline doc
                for arg1
            - arg2: some multiline doc
                for arg2
            """


# End of topic tree definition. Note that application may load
# more than one definitions provider.
