import unittest
from unittests import wtc
import wx.ribbon

#---------------------------------------------------------------------------

class ribbon_art_Tests(wtc.WidgetTestCase):

    def test_ribbon_art1(self):
        wx.ribbon.RIBBON_ART_TAB_SEPARATION_SIZE
        wx.ribbon.RIBBON_ART_PAGE_BORDER_LEFT_SIZE
        wx.ribbon.RIBBON_ART_PAGE_BORDER_TOP_SIZE
        wx.ribbon.RIBBON_ART_PAGE_BORDER_RIGHT_SIZE
        wx.ribbon.RIBBON_ART_PAGE_BORDER_BOTTOM_SIZE
        wx.ribbon.RIBBON_ART_PANEL_X_SEPARATION_SIZE
        wx.ribbon.RIBBON_ART_PANEL_Y_SEPARATION_SIZE
        wx.ribbon.RIBBON_ART_TOOL_GROUP_SEPARATION_SIZE
        wx.ribbon.RIBBON_ART_GALLERY_BITMAP_PADDING_LEFT_SIZE
        wx.ribbon.RIBBON_ART_GALLERY_BITMAP_PADDING_RIGHT_SIZE
        wx.ribbon.RIBBON_ART_GALLERY_BITMAP_PADDING_TOP_SIZE
        wx.ribbon.RIBBON_ART_GALLERY_BITMAP_PADDING_BOTTOM_SIZE
        wx.ribbon.RIBBON_ART_PANEL_LABEL_FONT
        wx.ribbon.RIBBON_ART_BUTTON_BAR_LABEL_FONT
        wx.ribbon.RIBBON_ART_TAB_LABEL_FONT
        wx.ribbon.RIBBON_ART_BUTTON_BAR_LABEL_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_LABEL_DISABLED_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_HOVER_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_HOVER_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_HOVER_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_HOVER_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_ACTIVE_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_ACTIVE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_ACTIVE_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_ACTIVE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_BUTTON_BAR_ACTIVE_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_FACE_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_HOVER_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_HOVER_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_HOVER_FACE_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_ACTIVE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_ACTIVE_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_ACTIVE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_ACTIVE_FACE_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_DISABLED_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_DISABLED_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_DISABLED_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_BUTTON_DISABLED_FACE_COLOUR
        wx.ribbon.RIBBON_ART_GALLERY_ITEM_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_TAB_LABEL_COLOUR
        wx.ribbon.RIBBON_ART_TAB_SEPARATOR_COLOUR
        wx.ribbon.RIBBON_ART_TAB_SEPARATOR_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_CTRL_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TAB_CTRL_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_HOVER_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_TAB_HOVER_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TAB_HOVER_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_ACTIVE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_TAB_ACTIVE_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_ACTIVE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TAB_ACTIVE_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TAB_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_BORDER_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_MINIMISED_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_MINIMISED_BORDER_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_LABEL_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_LABEL_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_LABEL_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_HOVER_LABEL_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_HOVER_LABEL_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_HOVER_LABEL_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_MINIMISED_LABEL_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_ACTIVE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_ACTIVE_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_ACTIVE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_PANEL_ACTIVE_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_HOVER_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_HOVER_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_PAGE_HOVER_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOLBAR_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_TOOLBAR_HOVER_BORDER_COLOUR
        wx.ribbon.RIBBON_ART_TOOLBAR_FACE_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_HOVER_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_HOVER_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_HOVER_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_HOVER_BACKGROUND_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_ACTIVE_BACKGROUND_TOP_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_ACTIVE_BACKGROUND_TOP_GRADIENT_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_ACTIVE_BACKGROUND_COLOUR
        wx.ribbon.RIBBON_ART_TOOL_ACTIVE_BACKGROUND_GRADIENT_COLOUR


    def test_ribbon_art2(self):
        wx.ribbon.RIBBON_SCROLL_BTN_LEFT
        wx.ribbon.RIBBON_SCROLL_BTN_RIGHT
        wx.ribbon.RIBBON_SCROLL_BTN_UP
        wx.ribbon.RIBBON_SCROLL_BTN_DOWN
        wx.ribbon.RIBBON_SCROLL_BTN_DIRECTION_MASK
        wx.ribbon.RIBBON_SCROLL_BTN_NORMAL
        wx.ribbon.RIBBON_SCROLL_BTN_HOVERED
        wx.ribbon.RIBBON_SCROLL_BTN_ACTIVE
        wx.ribbon.RIBBON_SCROLL_BTN_STATE_MASK
        wx.ribbon.RIBBON_SCROLL_BTN_FOR_OTHER
        wx.ribbon.RIBBON_SCROLL_BTN_FOR_TABS
        wx.ribbon.RIBBON_SCROLL_BTN_FOR_PAGE
        wx.ribbon.RIBBON_SCROLL_BTN_FOR_MASK

        wx.ribbon.RIBBON_BUTTON_NORMAL
        wx.ribbon.RIBBON_BUTTON_DROPDOWN
        wx.ribbon.RIBBON_BUTTON_HYBRID
        wx.ribbon.RIBBON_BUTTON_TOGGLE

        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_SMALL
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_MEDIUM
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_LARGE
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_SIZE_MASK

        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_NORMAL_HOVERED
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_DROPDOWN_HOVERED
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_HOVER_MASK
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_NORMAL_ACTIVE
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_DROPDOWN_ACTIVE
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_ACTIVE_MASK
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_DISABLED
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_TOGGLED
        wx.ribbon.RIBBON_BUTTONBAR_BUTTON_STATE_MASK

        wx.ribbon.RIBBON_GALLERY_BUTTON_NORMAL,
        wx.ribbon.RIBBON_GALLERY_BUTTON_HOVERED,
        wx.ribbon.RIBBON_GALLERY_BUTTON_ACTIVE,
        wx.ribbon.RIBBON_GALLERY_BUTTON_DISABLED


    def test_ribbon_art3(self):
        art = wx.ribbon.RibbonMSWArtProvider()


    def test_ribbon_art4(self):
        art = wx.ribbon.RibbonAUIArtProvider()


    def test_ribbon_art5(self):
        art = wx.ribbon.RibbonAUIArtProvider()
        clone = art.Clone()
        art.Flags
        art.GetFlags()
        art.GetFlags()


    def test_ribbon_art6(self):
        self.assertTrue(
            wx.ribbon.RibbonDefaultArtProvider in [wx.ribbon.RibbonMSWArtProvider,
                                                   wx.ribbon.RibbonAUIArtProvider])

    def test_ribbon_art7(self):
        bar = wx.ribbon.RibbonBar(self.frame)
        art = bar.GetArtProvider()
        p, s, t = art.GetColourScheme()

        assert isinstance(p, wx.Colour)
        assert isinstance(s, wx.Colour)
        assert isinstance(t, wx.Colour)


#---------------------------------------------------------------------------

if __name__ == '__main__':
    unittest.main()
