# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Set which Vagrant "box" (base image) to use, and tell it how to set up the
  # VM, packages to install, etc.
  config.vm.box = "debian/jessie64"
  config.vm.provision :shell, path: "bootstrap.sh"

  # Additional parameters for the VM
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
  end

  # Share the Phoenix/dist folder so the VM can get the source tarball and has
  # a place to put the build results.
  config.vm.synced_folder "../../dist", "/home/vagrant/dist"

end
